### ISSUE TITLE
Black vertical bar on the left side of XFWM decorations.

### ISSUE THREAD

**Issue by raulbonifacio** [md2222/W9-Dark#2]
Hi, thank you for your attention! 

I've been having (maybe) an issue with the XFWM window decorations on inactive windows. There's a black bar on the left side and I'm not sure if it's intended or not. I tried with different configurations but bar persists.

Is this behavior intended?

Nice theme btw!

![bar](https://user-images.githubusercontent.com/42476919/219907233-b90f9a0f-39ee-492f-aaed-46a0cab9b45f.png)

**Comment by md2222** [comment]
It's a bug. Fixed in 0.37. File /W9-Dark/xfwm4/top-left-inactive.xpm.
Thank you for message.

**Comment by raulbonifacio** [comment]
Thank you so much!
